apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: multi-tier-app
  labels:
    app: backend
    tier: backend
spec:
  selector:
    app: backend
    tier: backend
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  type: ClusterIP
