apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: multi-tier-app
  labels:
    app: database
    tier: database
spec:
  selector:
    app: database
    tier: database
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  type: ClusterIP
